
name: Testing robot framework

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: docker run --user='root' -v `pwd`/reports:/opt/robotframework/reports:Z -v `pwd`/test:/opt/robotframework/tests:Z -e BROWSER=chrome ppodgorsek/robot-framework:latest

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: test_reports
          path: reports